# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'flashhang-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Auth0', '~> 1.0'
  pod 'Firebase/Core'

  # Pods for flashhang-iOS

  target 'flashhang-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
